main: beatengine.BukkitServerInfo
name: ServerInfo
version: 1.0
author: BeatEngine
description: Info Plugin.
api-version: 1.16
website: https://github.com/BeatEngine/bukkit
commands:
  kit:
    description: Server Info
    usage: /serverinfo